
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-batch
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  batch:
    jdbc:
      initialize-schema: always